export const languages = {
  en: "English",
  fr: "Français",
};

export const defaultLang = "fr";

export const ui = {
  en: {
    replayGame: "Replay Game",
    seeHistory: "See History",
    clearHistory: "Clear History",
    yes: "Yes",
    no: "No",
    newGame: "New Game",
    history: "History",
    categories: "Categories",
    allSelected: "All selected by default",
    timer: "Timer",
    others: "Others",
    enabled: "Enabled",
    timerEnabled: "Timer enabled",
    timerDuration: "Timer duration",
    autoShowAnswer: "Auto show answer",
    durationSeconds: "Duration (seconds)",
    numberOfQuestions: "Number of questions",
    maximumNumberOfQuestions: "Maximum number of questions",
    "error.autoShowAnswer": "Auto show answer requires timer to be enabled",
    "error.noQuestions": "No questions found for the selected categories",
    startGame: "Start Game",
    questionsAvailable: "questions available",
    showAnswer: "Show Answer",
    nextQuestion: "Next Question",
    showHint: "Show Hint",
    allAnswered: "Congratulations! You have answered all the questions for the current game.",
    allAnswered2: "You can start a new game or see the history.",
    "categoryEnum.general": "General",
    "categoryEnum.blind-test": "Blind Test",
    "categoryEnum.movies": "Movies",
    "categoryEnum.cartoons": "Cartoons",
    "categoryEnum.celebrities-qc": "Celebrities (QC)",
    "categoryEnum.celebrities": "Celebrities",
    "categoryEnum.math": "Math",
    "categoryEnum.logo": "Logo",
    "categoryEnum.rebus": "Rebus",
    "categoryEnum.translated-lyrics-fr": "Translated Lyrics (EN -> FR)",
    "categoryEnum.translated-lyrics-en": "Translated Lyrics (EN -> FR)",
    "categoryEnum.spelling": "Spelling",
    "categoryEnum.animals": "Animals",
    "categoryEnum.video-games": "Video Games",
    "categoryEnum.four-pics-one-word": "Four Pics One Word",
    "categoryEnum.for-kids": "For Kids",
    "difficulty.1": "Easy",
    "difficulty.2": "Medium",
    "difficulty.3": "Hard",
  },
  fr: {
    replayGame: "Rejouer",
    seeHistory: "Voir l'historique",
    clearHistory: "Effacer l'historique",
    yes: "Oui",
    no: "Non",
    newGame: "Nouvelle Partie",
    history: "Historique",
    categories: "Catégories",
    allSelected: "Tous sélectionnés par défaut",
    timer: "Chronomètre",
    others: "Autres",
    enabled: "Activé",
    timerEnabled: "Chronomètre activé",
    timerDuration: "Durée du chronomètre",
    autoShowAnswer: "Afficher la réponse automatiquement",
    durationSeconds: "Durée (secondes)",
    numberOfQuestions: "Nombre de questions",
    maximumNumberOfQuestions: "Maximum number of questions",
    "error.autoShowAnswer": "L'affichage automatique de la réponse nécessite que le chronomètre soit activé",
    "error.noQuestions": "Aucune question trouvée pour les catégories sélectionnées",
    startGame: "Commencer la Partie",
    questionsAvailable: "questions disponibles",
    showAnswer: "Afficher la Réponse",
    nextQuestion: "Question Suivante",
    showHint: "Afficher l'Indice",
    allAnswered: "Félicitations! Vous avez répondu à toutes les questions pour la partie en cours",
    allAnswered2: "Vous pouvez commencer une nouvelle partie ou voir l'historique",
    "categoryEnum.general": "Général",
    "categoryEnum.blind-test": "Blind Test",
    "categoryEnum.movies": "Films",
    "categoryEnum.cartoons": "Dessins animés",
    "categoryEnum.celebrities-qc": "Célébrités (QC)",
    "categoryEnum.celebrities": "Célébrités",
    "categoryEnum.math": "Mathématiques",
    "categoryEnum.logo": "Logo",
    "categoryEnum.rebus": "Rébus",
    "categoryEnum.translated-lyrics-fr": "Paroles Traduites (FR -> EN)",
    "categoryEnum.translated-lyrics-en": "Paroles Traduites (EN -> FR)",
    "categoryEnum.spelling": "Orthographe",
    "categoryEnum.animals": "Animaux",
    "categoryEnum.video-games": "Jeux Vidéo",
    "categoryEnum.four-pics-one-word": "Quatre Images Un Mot",
    "categoryEnum.for-kids": "Pour Enfants",
    "difficulty.1": "Facile",
    "difficulty.2": "Moyen",
    "difficulty.3": "Difficile",
  },
} as const;
